version: '3'
services:
  app:
    build: .
    container_name: flask_app
    command: python api.py
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    restart: unless-stopped
    links:
      - db
  db:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_DATABASE=memory_control
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongodbdata:/data/db
    ports:
      - 27017:27017

volumes:
  mongodbdata:
    driver: local